### ISSUE TITLE
Differences from aphrodite

### ISSUE THREAD

**Issue by nodkrot** [planttheidea/jile#1]
How is this different from https://github.com/Khan/aphrodite?

**Comment by planttheidea** [comment]
I hadn't seen this project prior, but it looks like it tries to accomplish the same goals. The main differences I see are syntax related, jile is much more a WYSWYG output whereas there is magic that aphrodite is doing behind-the-scenes (the @font-face declarations, the way it adds !important to content declarations, etc.). I did notice that it's use of inline-style-prefix-all gives it a much smaller footprint, so I may consider switching to that (most of the bulk of the UMD build is using regular old inline-style-prefix). 

The biggest thing I don't dig is the hashing and hash reconciliation mechanism it has. Forcing every style in every render to make a `css()` method call vs just applying a single consistent hash (which jile does) is a performance hit. I'm also not seeing the "crazy selector" examples, so I don't know how it would handle `.parent > .directChild:first-of-type`, whereas in `jile` it allows all possible selector types. Not saying it's not supported, just not seeing it called out, and that can save a lot of unnecessary class declarations over time.

Overall I respect the project (I knew I wasn't the first one with this idea), but I still think `jile` is more straightforward because of its more WYSWYG approach. Admittedly, though, I am biased. :smile:

**Comment by nodkrot** [comment]
Thank you for the response! 
I'm generally looking into css inside javascript approaches and I found a lot of interesting solutions. If you are interested checkout [jss](https://github.com/jsstyles/jss) and [react-jss](https://github.com/jsstyles/react-jss), also [Material UI](https://github.com/callemall/material-ui) and [css-modules](https://github.com/css-modules/css-modules).
These projects including yours can potentially solve a problem of building a complete stand alone component (ex. button). The following problems that I'm still thinking about are theming and mixins/functions (similar to SASS). Do you have any ideas/thoughts on strategies on how to solve these problems with these new ways of CSS inside javascript?
Material UI has some interesting patterns but they are totally inline styles :/ (not sure how I feel about this)

**Comment by planttheidea** [comment]
You call out some excellent projects, actually I was originally inspired by jss (react-jss just provides some syntactic sugar on it). If I understand your question, only something like jss / aphrodite / jile would handle what you're looking for because they are pure JS. Anything that requires CSS (such as css-modules) requires a separate import / require / script tag, which is a hassle for the consumer of the component. Material UI (like Radium) being only inline styles has limitations, not the full power of CSS styles.

The ability to have themes as well as mixins / functions would really be more an aspect of the component than the styling library, however the styling library you choose would dictate the syntax developers using your component would use. When I've done these kinds of self-contained components, it usually goes something like this:
- Build the component and provide a default styles object (no configuration necessary for the minimum viable product)
- Accept a "styles" property (or whatever you want to call it) that is an object of the styles the user wants to apply to the component
- Merge your styles and the styles they pass (with the spread operator, `{...defaultStyles, ...userDefinedStyles}`) and the resulting object would be what is passed to your styling library for render

jss / aphrodite / jile would all work for this purpose, however with the syntaxes being different you just need to call out in your documentation the object you expect in that styles property. I know this explanation is a little generic, but there are a multitude of ways you can approach the task you describe. Hope this was helpful.

**Comment by nodkrot** [comment]
Explanation is great, but to elaborate further, for example a button can be used in multiple places and constantly passing a theme object to a button property seems very redundant. Material UI is using context (http://www.material-ui.com/#/customization/themes) to keep theming global, otherwise you can just have a JSON with all styles and import it on deep components. 
If I have, for example, 12 self-contained components in my project (Button, Alert, Link, ...) would jile append 12 style tags to the header?

**Comment by planttheidea** [comment]
If you want a consistent theme setup, you would create a higher-order component with that predefined theme and then use that component everywhere ... it's a common implementation, I apologize if it came across like I was advocating for passing objects in every time (that defeats the purpose of a component). Specific to Material UI, I personally don't like the `context`-based implementation ... something more along the lines of a decorator that traverses all nested children is much cleaner (much like how Radium works), but that is an implementation detail.

In regards to your more specific question, yes each component type would have its own dedicated style tag. If you're worried about tracing back styles while developing, I actually don't inject `<style>` tags when `NODE_ENV` is not `production`, but instead inject a `<link>` tag where the `href` is a Blob. This allows you to more easily trace back the styles that are applied in your devtools. The `<style>` tags are used when `NODE_ENV=production` for performance reasons.
